### ISSUE TITLE
Fix failing security check in ci

### ISSUE THREAD

**Issue by mattsse** [ChainSafe/PINT#101]
## Issue summary

- build fails because of detected vulnerabilities which are related to outdated deps (nalgebra)
- Should be done in conjunction with updating all upstream substrate/polkadot deps and address potential breaking changes

## Other information and links

-

**Comment by clearloop** [comment]
dup with #87

**Comment by mattsse** [comment]
This is due to an outdated version of cranelift which is pulled in by wasmtime in substrate.
substrate master is already upgraded, should be resolved soon

https://github.com/paritytech/substrate/blob/master/client/executor/wasmtime/Cargo.toml#L25

**Comment by mattsse** [comment]
after #107 , the audit fails due to  https://rustsec.org/advisories/RUSTSEC-2021-0070, 
nalgebra is used in `linregress` which got bump yesterday https://github.com/n1m3/linregress/blob/master/Cargo.toml to 0.4.2, substrate's frame-system still uses 0.4.0 though, https://github.com/paritytech/substrate/blob/c93ef27486e5f14696e5b6d36edafea7936edbc8/frame/benchmarking/Cargo.toml

This will be bumped as well eventually.

**Comment by mattsse** [comment]
closed with #158
