### ISSUE TITLE
add pallet session support

### ISSUE THREAD

**Issue by mattsse** [ChainSafe/PINT#109]
## Issue summary

- this will be required in order to configure the aura authorities 

## Other information and links

- Ref #107 #103

**Comment by clearloop** [comment]
So, #103 is abandoned? Let me try to fix the CI in #103

**Comment by mattsse** [comment]
I'd like to keep this separate, 
#107 for updating all the deps
and this one for switching from basic proof of validity to aura with collator mgmt
