### ISSUE TITLE
CI fails to fetch patches

### ISSUE THREAD

**Issue by mattsse** [ChainSafe/PINT#112]
## Issue summary

- the CI fails to fetch patches due to `paritytech//{substrate, polkadot, cumulus}` not being valid repository names. the double slash is required in the patches, because cargo requires patch url's to be different, https://github.com/rust-lang/cargo/issues/5478#issuecomment-387171359

## Other information and links

-

**Comment by clearloop** [comment]
Actually, we don't have to patch resources in `Cargo.toml`, we can just modify the commit hashes in `Cargo.lock` and it has the same result since we are just patching substrate like repos

**Comment by mattsse** [comment]
Yeah, that's what the `patch` section does, and you're not supposed to touch the lock file -.-
If we'd manage to get patches to work in the CI, it will make it so much easier to upgrade stuff, because we now have to integrate 5 repos that depend on each other, not necessarily on the same branch/state
* cumulus (requires substrate, polkadot, grandpa)
* polkadot (requires substrate, grandpa)
* substrate
* chainlink (requires substrate)

**Comment by clearloop** [comment]
-.- (QAQ)

**Comment by clearloop** [comment]
The double slash works on my machine with `cargo 1.52.0-nightly`

**Comment by mattsse** [comment]
Same here, my guess is that this is due:

> failed to authenticate when downloading repository: ssh://git@github.com/paritytech//grandpa-bridge-gadget

mb related https://github.com/rust-lang/cargo/issues/3900  https://github.com/rust-lang/cargo/issues/1851
https://doc.rust-lang.org/cargo/appendix/git-authentication.html

**Comment by clearloop** [comment]
The weird thing is docker works fine

**Comment by clearloop** [comment]
Use git CLi solves 

```
Caused by:
  failed to authenticate when downloading repository: ssh://git@github.com/paritytech//cumulus

  * attempted ssh-agent authentication, but no usernames succeeded: `git`
```

But new error

```
  fatal: remote error: 
    paritytech//polkadot is not a valid repository name
    Visit https://support.github.com/ for help
```

Maybe we can do a trick replacing the URI while git fetching the repos
