### ISSUE TITLE
Migrate non-calls pallets to `primitives/`

### ISSUE THREAD

**Issue by clearloop** [ChainSafe/PINT#116]
## Issue summary

For example

- `pallets/asset-depository`
- `pallets/price-feed`
- `pallets/xcm-asset-support`

They are not pallets actually, some of them might even don't need to be constructed with the `#[pallet]`

## Other information and links

- #81

**Comment by mattsse** [comment]
That's reasonable, I'm also about to submit a PR that creates a `primitives` crate for all the shared types/traits.
