### ISSUE TITLE
polkadot-launch is broken in CI caused by a conflict check added in #107

### ISSUE THREAD

**Issue by clearloop** [ChainSafe/PINT#127]
## Issue summary

https://github.com/ChainSafe/PINT/blob/a8f197256e293d1caebc79fc828b6ccff1e76e26/node/src/cli.rs#L57-L66

Modify the `/config.json`
 - or pr `polkadot-launch`
 - or remove the conflict check

**Comment by clearloop** [comment]
https://github.com/paritytech/polkadot-launch/blob/2844f6534741dca6f6563e4b2ce69964c5d3ffd1/src/spawn.ts#L118

Both `--parachain-id` and `--chain` are required in `polkadot-launch` now

**Comment by clearloop** [comment]
https://github.com/paritytech/cumulus/blob/9d9ed1bc84f2980a2d4cd56ca1a1e0e420f03581/polkadot-parachains/src/cli.rs#L77-L78

Why set conflict in #107? @mattsse

**Comment by mattsse** [comment]
I see,
interestingly the template `conflicts_with` https://github.com/substrate-developer-hub/substrate-parachain-template/blob/master/node/src/cli.rs#L62

Yes this restriction doesn't make a lot of sense, removing the attributes will fix this.

**Comment by clearloop** [comment]
> Do you want to take this on?

Sure, #123 requires this to test
