### ISSUE TITLE
extract common config types to a common crate

### ISSUE THREAD

**Issue by mattsse** [ChainSafe/PINT#156]
## Issue summary

in preparation of multiple runtime configurations we should extract commonly used types to a `common` crate within `runtime`, this may include
- common runtime parameter types (RuntimeBlockWeights, ...)
- balance unit types an helper functions (unit, microunit, milliunit...)
- anything we can precompile for multiple runtimes

## Other information and links

-

**Comment by clearloop** [comment]
We should do this together when we have different runtimes, for example:

- PINT for rococo
- PINT for kusama
- PINT for polkadot

?

**Comment by mattsse** [comment]
> We should do this together when we have different runtimes, for example:
> 
> * PINT for rococo
> * PINT for kusama
> * PINT for polkadot
> 
> ?

instead of rococo, we use chachacha and/or dev runtime.
But we'd need to name them first, or we simply use `pint-polkadot`, `pint-kusama`, `pint-dev` for the time being,

**Comment by clearloop** [comment]
> But we'd need to name them first, or we simply use pint-polkadot, pint-kusama, pint-dev for the time being,

Yep, and  `pint-polkadot`, `pint-kusama`, `pint-dev` are really efficiencient
