### ISSUE TITLE
configure xcm call weights as constants for different runtimes

### ISSUE THREAD

**Issue by mattsse** [ChainSafe/PINT#159]
## Issue summary

- [ ] add weights for xcm calls used on relay chain (kusama/polkadot), can those runtimes (more importantly their weight impls) be accessed in PINT chain spec?
- [ ] check whether the supported xcm calls (proxy, staking) are independent of the input parameters

## Other information and links

- Ref https://github.com/ChainSafe/PINT/pull/155#discussion_r662633737_

**Comment by clearloop** [comment]
Just realize the `staking_configs` and `proxy_configs` should be dynamic in case of supporting different chains.

Maybe a double map

```rust
pub type Proxies<T: Config> = StorageDoubleMap<
    _,
    Blake2_128Concat,
    AssetId,
    Twox64Concat,
    ParaId,
    ProxyConfig,
    ValueQuery,
>;
```

**Comment by mattsse** [comment]
Closing this since this will be supported by polkadot with upcoming xcm benchmarking pipeline directly
