### ISSUE TITLE
Allow fee payment with different assets.

### ISSUE THREAD

**Issue by mattsse** [ChainSafe/PINT#167]
Since depositing xcm assets and converting them into PINT is a two step process, payment for tx in multiple currencies should be supported.
We always have at least one price available for every assets that was registered. which should be the exchange rate to charge the user. Default currency is PINT token.

Ideally this should be done with a custom pallet that implements `TransactionPayment`

Ref #143 #88 
_Originally posted by @mattsse in https://github.com/ChainSafe/PINT/issues/146#issuecomment-874642658_

**Comment by clearloop** [comment]
> We always have at least one price available for every assets that was registered

Note: special case for `InitialPriciPair` https://github.com/ChainSafe/PINT/blob/8c20762ed728e4b8cbb8085d45f1ba853509f680/pallets/price-feed/src/lib.rs#L85 when no feed has been submitted

**Comment by mattsse** [comment]
This is now possible with relative price pairs that were introduce with `NavProvider` in #248
