### ISSUE TITLE
Empty balances in `AccountData` for initial accounts in javascript API

### ISSUE THREAD

**Issue by clearloop** [ChainSafe/PINT#169]
## Issue summary

In Apps:

`Developers -> Storage -> Balances -> account`

We'll get empty balances for account Alice, it should return the PINT record of Alice

## Other information and links

- #160

**Comment by mattsse** [comment]
how does the keyring setup look like?

**Comment by clearloop** [comment]
> how does the keyring setup look like?

We can just test it with Apps, we can get the balances of an account in the `Accounts` page, but not expected in the `Extrinsic` page

**Comment by mattsse** [comment]
If you use the setup described in the updated readme after #172 , does this still happen?

**Comment by clearloop** [comment]
> If you use the setup described in the updated readme after #172 , does this still happen?

Do you mean without `polkadot-launch`? I'll back to this issue soon, this doesn't block #160 anymore, now I'm handling the API of `orml-tokens` ref https://github.com/open-web3-stack/open-runtime-module-library/issues/499

**Comment by clearloop** [comment]
The `AccountData` are stored in `frame_system` and it is by design and intentional
