### ISSUE TITLE
XCM transfer broken after #164

### ISSUE THREAD

**Issue by clearloop** [ChainSafe/PINT#176]
## Issue summary

- `assetIndex.removeAsset`
```
assetIndex.removeAsset failed: remoteAssetManager.XcmError:  Error occurred during XCM  
```

- `remoteAssetManager.sendAddProxy`

```
remoteAssetManager.sendAddProxy failed: remoteAssetManager.FailedToSendAddProxyXcm:  Thrown when sending an Xcm `pallet_proxy::add_proxy` failed
```

- `remoteAssetManager.sendBond`

```
remoteAssetManager.sendBond failed: remoteAssetManager.FailedToSendBondXcm:  Thrown when sending an Xcm `pallet_staking::bond` failed
```

---

Saw nothing changed outside `asset-index` and `asset-registry` but the XCM transfers start to be failed, the only diff in remote-asset-manager is a modification of a field in `transfer-asset`

## Other information and links

-

**Comment by mattsse** [comment]
this rather looks like a Relay <-> Para connectivity by `T::XcmSender::send_xcm(dest, xcm)`. 

Sure PINT is already a parachain when you're running these commands?

**Comment by clearloop** [comment]
> Sure PINT is already a parachain when you're running these commands?

Reasonable, I'll add a parachain check in e2e tests

**Comment by mattsse** [comment]
We talked about the `finalized` argument of polkadot-launch a while back, probably worth checking if this is helpful in that context.

**Comment by clearloop** [comment]
> We talked about the `finalized` argument of polkadot-launch a while back, probably worth checking if this is helpful in that context.

Actually, the txs fail even after finalizing, for the finalization check, we already have in #153

**Comment by clearloop** [comment]
> finalized argument of polkadot-launch 

This https://github.com/paritytech/polkadot-launch/blob/6acc9187db0d1e2174cf3212a5ce8e80a34b47d3/config.json#L86 argument?

**Comment by mattsse** [comment]
> > finalized argument of polkadot-launch
> 
> This https://github.com/paritytech/polkadot-launch/blob/6acc9187db0d1e2174cf3212a5ce8e80a34b47d3/config.json#L86 argument?

yeah, https://github.com/paritytech/polkadot-launch/blob/cc3a1e5da490a8098039c5dec000c1ba89a2b7ae/README.md#finalization but I guess this is only for single txs and not the whole parachain onboarding process, however we're already waiting for the LAUNCH COMPLETE message, right https://github.com/ChainSafe/PINT/blob/main/js/finalize/index.ts#L11 ?

Was this perhaps introduced in #158 ?

**Comment by clearloop** [comment]
I thought about if it is caused by the upgrading, but 8c20762ed728e4b8cbb8085d45f1ba853509f680 still can run XCM transfers

**Comment by clearloop** [comment]
https://github.com/ChainSafe/PINT/pull/164/commits/f50b967711e4a3d6e34832ee884d9712bc3f43d3 still works LOL

**Comment by mattsse** [comment]
is it this: https://github.com/ChainSafe/PINT/blame/main/node/src/chain_spec.rs#L97 ?

**Comment by clearloop** [comment]
> is it this: https://github.com/ChainSafe/PINT/blame/main/node/src/chain_spec.rs#L97 ?

Not sure, #172 works before merge, let me re-check this from the commit history of #164 QAQ

**Comment by clearloop** [comment]
API changed in https://github.com/ChainSafe/PINT/blame/main/pallets/asset-index/src/lib.rs#L234 and javascript side just submitted the wrong codec of `location`

**Comment by mattsse** [comment]
> API changed in https://github.com/ChainSafe/PINT/blame/main/pallets/asset-index/src/lib.rs#L234 and javascript side just submitted the wrong codec of `location`

Can we close this @clearloop ?
