### ISSUE TITLE
Use initial PricePair for assets without feed

### ISSUE THREAD

**Issue by clearloop** [ChainSafe/PINT#180]
## Issue summary

When we add assets without existed feed now after #106, but for `deposit` asset or other operations of the assets without feed still require PricePair

## Other information and links

-

**Comment by mattsse** [comment]
This is indeed a feature that we should add, another questions around that issue:
* should we track the latest submission and add a validity period (blocks)? but what should happen if the latest block exceeds this period? freezing the asset in such a case will introduce lots of complications...

**Comment by clearloop** [comment]
> should we track the latest submission and add a validity period (blocks)? but what should happen if the latest block exceeds this period? freezing the asset in such a case will introduce lots of complications...

Or we force checking if the matched feed has been submitted before adding assets? All PINT stuffs run after chainlink-feed, I think this is weird...

**Comment by clearloop** [comment]
This feature has already implemented in #160:

`get_price` will check the `initial_price` if feed not exists, it covers most of the calls in PINT which requires `feed`

I think we can move forward this issue to another which is about:

> should we track the latest submission and add a validity period (blocks)? but what should happen if the latest block exceeds this period? freezing the asset in such a case will introduce lots of complications...

**Comment by mattsse** [comment]
Agreed, but this needs some more research before we can make a decision on this.
