### ISSUE TITLE
Ensure liquid asset when `remove_asset` in `asset_index`

### ISSUE THREAD

**Issue by clearloop** [ChainSafe/PINT#183]
## Issue summary

Unexpected panic https://github.com/ChainSafe/PINT/blob/c478d8d005b681ee27911ba4186b48921be4159f/pallets/asset-index/src/lib.rs#L276 here

## Other information and links

-

**Comment by mattsse** [comment]
Can you give a bit more context about what the expected behavior would be?

**Comment by clearloop** [comment]
> Can you give a bit more context about what the expected behavior would be?

For example, if we run `remove_asset(ASSET_A: SAFT)`, PINT should throw an error like `Removing SAFT asset`, because the `remote_asset` only supports removing liquid assets

**Comment by clearloop** [comment]
The current implementation has no bug, other errors occurs in testing
