### ISSUE TITLE
Register PINT in orml_currencies in genesis

### ISSUE THREAD

**Issue by clearloop** [ChainSafe/PINT#184]
## Issue summary

The balances implementation in PINT is like

- orml_currencies
  - PINT ( asset_id: 1 )
  - orml_tokens

I'm not quite sure about what happens here, but I met a bunch of troubles about the value of balances while writing the e2e tests in #160 

One simple scene is :

- deposit PINT asset to the treasury which should have asset id `1`
- run `deposit(1_ASSET_ID, 100_Balances)`
- transaction failed because PINT is not recognized for the `Currency` in `asset-index`, even it configured PINT as the native token in runtime

---

1. Do we have to register PINT to orml_currencies?
2. Should `deposit` support PINT?

## Other information and links

- #182

**Comment by mattsse** [comment]
> 2. Should deposit support PINT?

Definitely not, this should be caught and in the `deposit` functions.

**Comment by mattsse** [comment]
> At launch, an initial allocation of PINT tokens will be granted to the Treasury.

**Comment by mattsse** [comment]
Is this still an issue? I think we can close this, since we already mint pint in genesis via `balances` pallet in the chain specs @clearloop ?
