### ISSUE TITLE
AssetIndex Pallet

### ISSUE THREAD

**Issue by dutterbutter** [ChainSafe/PINT#2]
The completion of this Epic requires the `AssetIndex` pallet to be completed with intended features and tested.   

## Implementation details
The AssetIndex pallet is responsible for tracking a set of assets and representing them in the form of an index. For each asset it stores a record containing:

- Asset ID - a unique identifier for the asset
- Location - where the asset exists (ie. which chain)
- Units - how many units of the asset are in the index
- Availability - whether the asset is liquid or not

## Acceptance Criteria
The completed pallet should have the following functionality:
-  [x] `add_asset`
-  [x] `remove_asset`
-  [x] `deposit`
-  [x] `withdraw`
-  [x] `complete_withdrawal`

**Comment by clearloop** [comment]
The pallet `asset-index` has been added in #29 with the method `add_asset`.

( It would be nice converting this issue into a GitHub Project
