### ISSUE TITLE
Simplify the RedemptionState machine

### ISSUE THREAD

**Issue by mattsse** [ChainSafe/PINT#263]
## Issue summary

Before initiated index withdrawals can be completed, a few conditions must be met:
- the redemption period must be over
- the remote balance can cover parachain xcm withdrawals.

Initiating a withdrawals succeeds regardless of the current remote balance. 
Since the withdrawal undergoes a redemption period, the actual assets only need to be available by this point/block.
Therefore we need to track all pending withdrawals and ensure that we can cover the xcm transfer once the period is over.
#244 and #245 describe why and how we would deal with unbonds, leading to an untangling of the whole xcm unbond process from individual withdrawals, so that from pov of asset-index the remote-asset manager merely functions as the tracker of all remote balances. So that the asset-index merely informs the manager about requested withdrawals and then basically waits until the redemption period is over. Meanwhile, the asset manager tracks incoming and outgoing assets xcm volume and reserves the total amount of outstanding redemptions on the remote free balance, either limiting new xcm `staking::bond` or issuing `staking::unbond` and `staking::withdraw` to remove staked assets. This will limit staking related xcm calls and simplify the redemption process.

**Comment by dutterbutter** [comment]
@mattsse @clearloop Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/PINT-6050fdbefec7550019a6100a/issues/ChainSafe/PINT/263?planning-poker)
