### ISSUE TITLE
Regenerate weights for all pallets

### ISSUE THREAD

**Issue by clearloop** [ChainSafe/PINT#266]
```
𝝺 WASMTIME_BACKTRACE_DETAILS=1 ./target/release/pint benchmark -p pallet_asset_index -e '*' --execution Wasm --wasm-execution Compiled --raw --output ./runtime/common/src/weights/pallet_asset_index.rs --chain pint-local                       
2021-08-18 15:44:45 assembling new collators for new session 0 at #0    
2021-08-18 15:44:45 assembling new collators for new session 1 at #0    
2021-08-18 15:44:46 panicked at 'Expected Ok(_). Got Err(
    <wasm:stripped>,
)', /Users/clearloop/code/PINT/pallets/asset-index/src/benchmarking.rs:72:9    
Error: Input("Error executing runtime benchmark: Other(\"Wasm execution trapped: wasm trap: unreachable\\nwasm backtrace:\\n    0: 0x22d9 - <unknown>!rust_begin_unwind\\n\")")
```

Could not generate weights caused by some wasm issue

_Originally posted by @clearloop in https://github.com/ChainSafe/PINT/issues/262#issuecomment-900895834_

## Issues

- #230 
- #261

**Comment by clearloop** [comment]
Error when `--extrinsic *`

**Comment by dutterbutter** [comment]
@clearloop @mattsse Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/PINT-6050fdbefec7550019a6100a/issues/ChainSafe/PINT/266?planning-poker)

**Comment by clearloop** [comment]
blocked by #268 , some benchmarks of pallet `asset-index` are not correct that can not run and generate weights.
