### ISSUE TITLE
Complete javascript types and fix e2e tests

### ISSUE THREAD

**Issue by clearloop** [ChainSafe/PINT#267]
## Issue summary

The e2e tests seems broken with cache of docker image

## Other information and links

-

**Comment by dutterbutter** [comment]
@clearloop @mattsse Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/PINT-6050fdbefec7550019a6100a/issues/ChainSafe/PINT/267?planning-poker)
