### ISSUE TITLE
Check origins for all pallets

### ISSUE THREAD

**Issue by clearloop** [ChainSafe/PINT#268]
### pallet-xcm

+ [ ] SendXcmOrigin -  `EnsureXcmOrigin<Origin, LocalOriginToLocation>`

### cumulus_pallet_dmp_queue

+ [ ] ExecuteOverweightOrigin - `frame_system::EnsureRoot<AccountId>`

### pallet_collator_selection

+ [ ] UpdateOrigin - `EnsureApprovedByCommittee`

### pallet_local_treasury

+ [ ] AdminOrigin - `frame_system::EnsureRoot<AccountId>`

### pallet_saft_registry

+ [ ] AdminOrigin - `frame_system::EnsureSigned<AccountId>`

### pallet_committee

+ [ ] ProposalSubmissionOrigin - `EnsureSigned<AccountId>`
+ [ ] ProposalExecutionOrigin - `EnsureMember<Self>`
+ [ ] ApprovedByCommitteeOrigin - `EnsureApprovedByCommittee`

### pallet_price_feed

+ [ ] AdminOrigin - `frame_system::EnsureRoot<AccountId>`

### pallet_asset_index

+ [ ] AdminOrigin - `frame_system::EnsureSigned<AccountId>`

### pallet_remote_asset_manager

+ [ ] AdminOrigin - `frame_system::EnsureSigned<AccountId>`

## Other information and links

- #104 
- #140

**Comment by dutterbutter** [comment]
@clearloop @mattsse Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/PINT-6050fdbefec7550019a6100a/issues/ChainSafe/PINT/268?planning-poker)
