### ISSUE TITLE
Timestamp asset-index deposits

### ISSUE THREAD

**Issue by mattsse** [ChainSafe/PINT#270]
## Issue summary

While the fee model has not been finalized yet, it will depend on how long LP contributions remained in the index. Therefore we need to timestamp (blocknumber) and record the LP’s AccountId is whenever PINT is minted to restrict the redemption of that PINT to the LP and to calculate fees associated with early redemption of the PINT.

- [ ] This can be solved by an additional storage map in `asset-index` (AccountId -> Vec<(Amount PINT, BlockNumber)>). in order to limit these contribution we should opt for a `DepositLimit` which restricts how many deposits can be active, as a precaution, so that we can use a `BoundedVec<(Amount PINT, BlockNumber), DepositLimit>`.  Since we already restrict the amount of allowed deposits, this list should not grow to large.
- [ ] upon redemption we need to consolidate the oldest deposits (first in the Vec) and remove those which are completely withdrawn and update the oldest in the list.
- [ ] Add Fee playholder trait, which should have the form of `redemption_fee(duration: BlockNumber, amount: Balance)` this will come on top of the base fee for the time being.

## Other information and links

-

**Comment by dutterbutter** [comment]
@mattsse @clearloop Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/PINT-6050fdbefec7550019a6100a/issues/ChainSafe/PINT/270?planning-poker)
