### ISSUE TITLE
Enforce Deposit Limits

### ISSUE THREAD

**Issue by mattsse** [ChainSafe/PINT#271]
## Issue summary

- Add a check to ensure sufficient contributions. There is already `DOTContributionLimit` which was intended to restrict the maximum amount of that DOT that can exist in the index, instead this should enforce both a minimum and maximum amount. This should be checked after determining the pint equivalent in `deposit`

## Other information and links

-

**Comment by dutterbutter** [comment]
@clearloop @mattsse Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/PINT-6050fdbefec7550019a6100a/issues/ChainSafe/PINT/271?planning-poker)
