### ISSUE TITLE
Mint asset when adding them via governance in add_asset

### ISSUE THREAD

**Issue by mattsse** [ChainSafe/PINT#276]
## Issue summary

As discussed the Governance committee decides the tokens that comprise the index, as well as the allocation of each, which will be set via `add_asset`, therefor `add_asset` should be treated as a minting operation for both PINT and the given asset, rather than a transfer as it's handled in `deposit`.
- [ ] mint PINT into the origin's account
- [ ] mint asset into the treasury account

## Other information and links

-

**Comment by dutterbutter** [comment]
@clearloop Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/PINT-6050fdbefec7550019a6100a/issues/ChainSafe/PINT/276?planning-poker)

**Comment by dutterbutter** [comment]
@mattsse Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/PINT-6050fdbefec7550019a6100a/issues/ChainSafe/PINT/276?planning-poker)

**Comment by clearloop** [comment]
- #146

**Comment by mattsse** [comment]
In the `add-asset` extrinsic, no. This is essentially a governance approved minting procedure.
