### ISSUE TITLE
Extend Weights traits for all extrinsics with benchmarks

### ISSUE THREAD

**Issue by mattsse** [ChainSafe/PINT#283]
## Issue summary

the asset-index already has complete benchmarking support for the extrinsics, but WeightsInfo trait currently lacks them.
- [ ] extend the `WeightsInfo` trait and update the weight attributes

## Other information and links

- #266

**Comment by dutterbutter** [comment]
@clearloop @mattsse Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/PINT-6050fdbefec7550019a6100a/issues/ChainSafe/PINT/283?planning-poker)
