### ISSUE TITLE
Integrate oracle pallet and add price feed

### ISSUE THREAD

**Issue by dutterbutter** [ChainSafe/PINT#30]
In order to exchange assets for PINT, the value of those assets as well as PINT’s NAV needs to be computed. To achieve this a price-feed service is required.

**Comment by mattsse** [comment]
For the time being an updated version of substrate v3 lives here [mattsse/chainlink-polkadot](https://github.com/mattsse/chainlink-polkadot/tree/substrate-v3)

There is also a draft for the callback implementation in the feed pallet: https://github.com/smartcontractkit/chainlink-polkadot/pull/51
