### ISSUE TITLE
Fix e2e tests after updating origins

### ISSUE THREAD

**Issue by clearloop** [ChainSafe/PINT#301]
## Issue summary

Most of e2e tests are using `Signed` origin for testing now, and the origins need to be updated after #268 

## Other information and links
-

**Comment by Redoudou** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/PINT-6050fdbefec7550019a6100a/issues/ChainSafe/PINT/301?planning-poker) with ZenHub @clearloop @mattsse
