### ISSUE TITLE
Return lists in benchmark_metadata in the new feature #295 provided

### ISSUE THREAD

**Issue by clearloop** [ChainSafe/PINT#314]
## Issue summary

https://github.com/ChainSafe/PINT/blob/ba099875df44579a946c8dbdc6e5b4d61a166770/runtime/dev/src/lib.rs#L824-L835

This returns an empty benchmark list that we can not fetching benchmarks in our client

## Other information and links
-  #295

**Comment by mattsse** [comment]
I guess the right syntax would be to add all of them like this

```rust
	list_benchmark!(list, extra, pallet_balances, Balances);
        list_benchmark!(list, extra, pallet_committee, Committee);
```

Not entirely sure about this yet
