### ISSUE TITLE
Add dispatchables for root origin

### ISSUE THREAD

**Issue by mattsse** [ChainSafe/PINT#324]
## Issue summary

- current saftregistry and assetindex require the origin to be signed, to mint/burn from the sender's account. This prevents us from using Root to execute this calls. Therefore
- [ ] Add additional `force_*` dispatchables (add_asset, add_saft, remove_asset) that mirror the existing ones but take an additional `recipient` parameter and `ensure_root`. For example `fn force_add_asset(..., recipient: AccountId) {ensure_root(origin)?;}`

## Other information and links

- Ref #317

**Comment by Redoudou** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/PINT-6050fdbefec7550019a6100a/issues/ChainSafe/PINT/324?planning-poker) with ZenHub @clearloop @mattsse
