### ISSUE TITLE
Fix the benchmarks of pallet saft-registry

### ISSUE THREAD

**Issue by clearloop** [ChainSafe/PINT#325]
`Self::nav()` broken, because no available assets yet, 

For could not `add_saft`, the reason is like the issue in https://github.com/ChainSafe/PINT/blob/810ea668ab826e0470de8c791ef83c41bf939f33/pallets/asset-index/src/tests.rs#L115, add another liquid asset will be able to fix it

_Originally posted by @clearloop in https://github.com/ChainSafe/PINT/issues/317#issuecomment-911320472_

Might need to add something like `create_feed` in #300 provided

**Comment by Redoudou** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/PINT-6050fdbefec7550019a6100a/issues/ChainSafe/PINT/325?planning-poker) with ZenHub @clearloop @mattsse
