### ISSUE TITLE
Queue proposals in e2e tests

### ISSUE THREAD

**Issue by clearloop** [ChainSafe/PINT#352]
## Issue summary

Most calls we current have need to propose and execute but not call with an account directly, so we need a new function to propose and vote extrinsic directly

- propose an extrinsic
- record the propose in storage
- vote for this proposal
- close and check result

## Other information and links

-

**Comment by Redoudou** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/PINT-6050fdbefec7550019a6100a/issues/ChainSafe/PINT/352?planning-poker) with ZenHub @clearloop @mattsse
