### ISSUE TITLE
Updates the docker images of polkadot and statemint

### ISSUE THREAD

**Issue by clearloop** [ChainSafe/PINT#360]
## Issue summary

Should follow the current version of PINT

## Other information and links

-

**Comment by Redoudou** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/PINT-6050fdbefec7550019a6100a/issues/ChainSafe/PINT/360?planning-poker) with ZenHub @clearloop @mattsse
