### ISSUE TITLE
TOB-PINT-3 - Data validation

### ISSUE THREAD

**Issue by Redoudou** [ChainSafe/PINT#363]
Missing decimal validation in the set_metadata function.
Description
The function set_metadata in figure 3.1 doesn't validate the decimals variable lower and upper bound. This allows the governance committee to set the decimals of a given asset to 0 or to a very high value, which are undesired.

The set_metadata function (PINT/pallets/asset-index/src/lib.rs#L472-L493

**Comment by clearloop** [comment]
The default decimals of our IndexToken is 12, we might need to update the nav calculation / tokens transformation logics along with this?

**Comment by clearloop** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/PINT-6050fdbefec7550019a6100a/issues/ChainSafe/PINT/363?planning-poker) with ZenHub @mattsse
