### ISSUE TITLE
TOB-PINT-11 -  Static extrinsic weight

### ISSUE THREAD

**Issue by Redoudou** [ChainSafe/PINT#368]
Remove static weights.

**Comment by clearloop** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/PINT-6050fdbefec7550019a6100a/issues/ChainSafe/PINT/368?planning-poker) with ZenHub @mattsse

**Comment by mattsse** [comment]
this is a dupe of #261 closing in favor of that one
