### ISSUE TITLE
Redundant register_asset extrinsic that can be used to register asset with PINT_ASSET_ID

### ISSUE THREAD

**Issue by Redoudou** [ChainSafe/PINT#369]
Remove redundant register_asset extrinsic

**Comment by clearloop** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/PINT-6050fdbefec7550019a6100a/issues/ChainSafe/PINT/369?planning-poker) with ZenHub @mattsse

**Comment by mattsse** [comment]
closing in favor of #383
