### ISSUE TITLE
No spam prevention for submitting governance proposals

### ISSUE THREAD

**Issue by Redoudou** [ChainSafe/PINT#372]

**Comment by clearloop** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/PINT-6050fdbefec7550019a6100a/issues/ChainSafe/PINT/372?planning-poker) with ZenHub @mattsse

**Comment by mattsse** [comment]
It is expected that one council member will be the lead and responsible for submitting proposal, so restrictions on the number of proposals are unexpected rn.
