### ISSUE TITLE
Constituents can vote in the same voting period they were added in

### ISSUE THREAD

**Issue by Redoudou** [ChainSafe/PINT#374]

**Comment by clearloop** [comment]
> 4 constituent members voted for and 0 voted against the proposal

Constituents only can vote against, for checking if a proposal is accepted, we only count the ayes of council members, maybe need to throw an error when a constituent voting aye

**Comment by clearloop** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/PINT-6050fdbefec7550019a6100a/issues/ChainSafe/PINT/374?planning-poker) with ZenHub @mattsse

**Comment by mattsse** [comment]
this is essentially the same as #373 
closing
