### ISSUE TITLE
Elevate priority of important operations

### ISSUE THREAD

**Issue by Redoudou** [ChainSafe/PINT#375]
Make extrinsincs related to governance either `DispatchClass::Mandatory` if possible or `Operational`

**Comment by mattsse** [comment]
This is essentially a dupe of #373

**Comment by clearloop** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/PINT-6050fdbefec7550019a6100a/issues/ChainSafe/PINT/375?planning-poker) with ZenHub @mattsse

**Comment by clearloop** [comment]
can add more logic on the checking of the weight to optimize this
