### ISSUE TITLE
Add remove member extrinsic

### ISSUE THREAD

**Issue by mattsse** [ChainSafe/PINT#394]
## Issue summary

- Currently there only exists an extrinsic to add new constituents 
- It should be possible to remove council/constituents via governance but always require at least `T::MinCouncilMembers` 

## Other information and links

-

**Comment by mattsse** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/PINT-6050fdbefec7550019a6100a/issues/ChainSafe/PINT/394?planning-poker) with ZenHub @clearloop

**Comment by clearloop** [comment]
we don't have call adding council, so as we adding a call remove council, the council members have no way to increase

**Comment by mattsse** [comment]
> we don't have call adding council, so as we adding a call remove council, the council members have no way to increase
> 
> there are two open seats for community member due to https://docs.polkadotindex.com/governance, mb we can modify `add_constituent` to `add_member` together

good idea.
