### ISSUE TITLE
Optimize helper method ownership

### ISSUE THREAD

**Issue by mattsse** [ChainSafe/PINT#403]
## Issue summary

- Review pallet's helper functions whether taking ownership of non copy types (`AccountId`) can be removed.

## Other information and links

-

**Comment by Redoudou** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/PINT-6050fdbefec7550019a6100a/issues/ChainSafe/PINT/403?planning-poker) with ZenHub @clearloop @mattsse
