### ISSUE TITLE
Remove proposals in ActiveProposals after closing/executing

### ISSUE THREAD

**Issue by clearloop** [ChainSafe/PINT#408]
## Issue summary

for the `ActiveProposals` storage in pallet committee, there are only insert logic but no remove logics

- should remove proposals in ActiveProposals after executing/closing

Or

- add status field to the `Proposal` type
- remove `ExecutedProposals`
- remove `ActiveProposals`

**Comment by Redoudou** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/PINT-6050fdbefec7550019a6100a/issues/ChainSafe/PINT/408?planning-poker) with ZenHub @clearloop @mattsse
