### ISSUE TITLE
Require liquid assets were sent to via XCM

### ISSUE THREAD

**Issue by mattsse** [ChainSafe/PINT#411]
## Issue summary

- Currently `add_asset` mints PINT + liquid assets a like, this assumes they were contributed. Instead, it should be enforced that these are reserve-backed transferred to PINT first.

## Other information and links

-

**Comment by Redoudou** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/PINT-6050fdbefec7550019a6100a/issues/ChainSafe/PINT/411?planning-poker) with ZenHub @clearloop @mattsse
