### ISSUE TITLE
Enforce existential deposit when minting PINT

### ISSUE THREAD

**Issue by mattsse** [ChainSafe/PINT#414]
## Issue summary

- `deposit_creating` may return a `PositiveImbalance` if the given amount is lower the existential deposit which is not an error, instead it should be enforced that the targeted account has the necessary balance after the deposit

## Other information and links

-

**Comment by Redoudou** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/PINT-6050fdbefec7550019a6100a/issues/ChainSafe/PINT/414?planning-poker) with ZenHub @clearloop @mattsse
