### ISSUE TITLE
More tests for the timeout of proposals

### ISSUE THREAD

**Issue by clearloop** [ChainSafe/PINT#418]
lgtm.
But we should definitely follow up with some additional tests for timeout out etc.

_Originally posted by @mattsse in https://github.com/ChainSafe/PINT/pull/410#pullrequestreview-762781876_

**Comment by clearloop** [comment]
https://github.com/ChainSafe/PINT/pull/410#issuecomment-926595604

**Comment by mattsse** [comment]
> [#410 (comment)](https://github.com/ChainSafe/PINT/pull/410#issuecomment-926595604)

that sounds about right!
