### ISSUE TITLE
Add update voting period extrinsic

### ISSUE THREAD

**Issue by mattsse** [ChainSafe/PINT#422]
The new call should only accept values in range of [7, 28], also this should only kick in after the current voting period has ended, so we probably need a storage slot to store the pending voting period until then.

needs a follow up to update the voting period if it's [7, 28] days

_Originally posted by @mattsse in https://github.com/ChainSafe/PINT/pull/421#pullrequestreview-764100449_

**Comment by clearloop** [comment]
If the upcoming proposals are persistent coming, the new `VotingPeriod` can be blocked forever, what about lock the ability of `propose` after the new VotingPeriod has applied to storage?

**Comment by clearloop** [comment]
This is absolutely a great catch, if `submit_proposal` ->  `short_the_voting_period` -> `add_new_member`, the voting attack will be possible again now.

The `PendingProposals` can be represent as proposals with `Active` status, we just need to refactor the storage of VotingPeriod like 

```
struct VotingPeriod {
  current: BlockNumber,
  next: Option<BlockNumber>,
}
```

And then once we close a proposal, if there is no active proposals, we modify the `current` of `VotingPeriod` to the `next` if exists

**Comment by mattsse** [comment]
yes, exactly.
I'd rather make this a separate storage value for `PendingVotingPeriod`
