### ISSUE TITLE
Improve test coverage for committee

### ISSUE THREAD

**Issue by mattsse** [ChainSafe/PINT#427]
## Issue summary

- review current test cov and add more edge case coverage 
- [ ] changed voting period
- [ ] valid voting periods

## Other information and links

-

**Comment by Redoudou** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/PINT-6050fdbefec7550019a6100a/issues/ChainSafe/PINT/427?planning-poker) with ZenHub @clearloop @mattsse
