### ISSUE TITLE
Github Actions don't have enough space storing our building cache

### ISSUE THREAD

**Issue by clearloop** [ChainSafe/PINT#47]
[Github Actions Cache Limits](https://github.com/actions/cache#cache-limits)

## Examples

* 074bd1897900a5d3ebceaee556e7af8de923964e, [No space left on device](https://github.com/ChainSafe/PINT/actions/runs/778519716)
* #41, [No space left on device](https://github.com/ChainSafe/PINT/actions/runs/779602549)

## Potential Solutions

* Remove Cache
* Use artifacts && Change CI

**Comment by ansermino** [comment]
CircleCI is also an option if you want more space, the [Forest](https://github.com/chainSafe/forest) team prefers it for Rust builds. Let me know if you want to explore that.

**Comment by clearloop** [comment]
> CircleCI is also an option if you want more space, the [Forest](https://github.com/chainSafe/forest) team prefers it for Rust builds. Let me know if you want to explore that.

Sure, I can write the config of circle-ci for PINT referring to [ChainSafe/forest/.circleci/config.yml](https://github.com/ChainSafe/forest/blob/main/.circleci/config.yml)
