### ISSUE TITLE
Construct Dockerfile

### ISSUE THREAD

**Issue by dutterbutter** [ChainSafe/PINT#6]
Include a Dockerfile for the node

**Comment by clearloop** [comment]
Hi @dutterbutter , we might need to configure `secrets.DOCKER_HUB_USERNAME` and `secrets.DOCKER_HUB_ACCESS_TOKEN` in `settings -> secrets` for publishing `pint:latest` to docker registry automatically everytime we update the main branch

**Comment by dutterbutter** [comment]
@clearloop I will add them to the repo! Thanks 🙌
