### ISSUE TITLE
Add ensure type configurations for various AdminOrigin's

### ISSUE THREAD

**Issue by mattsse** [ChainSafe/PINT#64]
## Issue summary

- Currently all `AdminOrigin`s are configured in the runtime as `EnsureRoot`, they should be configured with their own types (e.g. `EnsureCouncil`)

## Other information and links

-

**Comment by clearloop** [comment]
> I think what will also be required is something like `EnsureMember` that checks whether the origin is included in the memebers list of the comittee. 

I'm confused about why we separate `ProposalSubmissionOrigin` and `ProposalExecutionOrigin` but not just a `CouncilOrigin` or (`CouncilOrigin` and `ConstituentOrigin`)
