### ISSUE TITLE
Implement e2e testing

### ISSUE THREAD

**Issue by dutterbutter** [ChainSafe/PINT#81]
## Implementation details

Implement e2e testing to ensure everything works collectively (e.g. register assets, oracle setup, adding/depositing/withdrawing assets).

**Comment by clearloop** [comment]
- [ ] asset-depository
- [ ] asset-index
- [ ] committee
- [ ] local-treasury
- [ ] price-feed
- [ ] remote-asset-manager
- [ ] saft-registry
- [ ] xcm-asset-support
