### ISSUE TITLE
Fixed ParachainId

### ISSUE THREAD

**Issue by clearloop** [ChainSafe/PINT#84]
## Issue summary

Currently, we are using the default ParachainId generated by the pallet `parachain_info`, which is 100 and conflicts with `statemint`

We need a `ParachainId` ourselves.

## Other information and links

- https://github.com/paritytech/cumulus/blob/36c6da180a43f2decaa4d5f7c8147fcbf1a6d20e/polkadot-parachains/pallets/parachain-info/src/lib.rs#L51

**Comment by dutterbutter** [comment]
Closing for now.
