### ISSUE TITLE
Check if feed pair exists while adding asset in pallet asset index

### ISSUE THREAD

**Issue by clearloop** [ChainSafe/PINT#94]
## Issue summary

The call `add_asset` in pallet `asset-index` adds assets directly without checking if the matched feed pair exists which make the following calls like `deposit` could not execute

## Other information and links
- #93 
- https://github.com/ChainSafe/PINT/blob/4fcfc4fda293c1a973dd97ac8e1dd7010e4d944d/pallets/price-feed/src/tests.rs#L90

**Comment by mattsse** [comment]
The `add_asset` is an admin/council only function which mints the given amount of PINT token.

The asset/pint rate is essentially determined by the admin here. We could probably use this initial rate until a price feed exists for this asset?

**Comment by clearloop** [comment]
> The add_asset is an admin/council only function which mints the given amount of PINT token.

Understand this design, except the price feed probem, the other problem is, with `EnsureRoot` in our runtime configuration, 

* https://github.com/ChainSafe/PINT/blob/4fcfc4fda293c1a973dd97ac8e1dd7010e4d944d/runtime/src/lib.rs#L540

We could not run this extrinsic in production, because there is a line trying to unwrap the origin:

* https://github.com/ChainSafe/PINT/blob/4fcfc4fda293c1a973dd97ac8e1dd7010e4d944d/pallets/asset-index/src/lib.rs#L173

and unwrapping `RawOrigin::Root` will cause `BadOrigin`

---

> We could probably use this initial rate until a price feed exists for this asset?

I agree with this idea, I can implement this in #91 or we create another PR?

And this implementation will solve the problem I meet in #93 rn , configuring an initial rate in runtime, then I don't need to create a feed in the benchmarks of one specific pallet.

**Comment by mattsse** [comment]
This should be its own PR, because it requires some changes within either the price pair or asset index pallet I think,
I guess best way to go would be to add this initial rate as fallback when no price feed could be feed.
So this would mean on `add_asset` the PINT/asset pair is determined based on the given extrinsic arguments and inserted/updated as `PricePair` somewhere.
