### ISSUE TITLE
Set initial council members in runtime

### ISSUE THREAD

**Issue by clearloop** [ChainSafe/PINT#96]
## Issue summary

Note: The origin configuration of the pallet committee has been modified to `EnsureSigned` in #91, but we still don't have initial council members in the runtime configuration.

## Other information and links

- #94 
- #64 
https://github.com/paritytech/substrate/blob/37bb3ae7eb559afaf9c7dbf7fd99e08b282c8127/bin/node/runtime/src/lib.rs#L494

**Comment by clearloop** [comment]
After looking through the pallet committee again, I have two plans for setting the `ProposalSubmissionOrigin` and `ProposalExecutionOrigin`

* Council Members have these right ( with an `EnsureMember` Origin )
* Set new storage for storing the permitted origins ( new `Origin`s )

According to the development document of PINT, we have an account list for the initial members, I personally prefer to replace these  two origins with `EnsureMember` momentary which would be better than `EnsureRoot` for the upcoming tests

**Comment by mattsse** [comment]
> I personally prefer to replace these two origins with EnsureMember momentary which would be better than EnsureRoot

Agree!

> Set new storage for storing the permitted origins ( new Origins )

Can you elaborate on this? Can we use the `Members` storage of the committee?

**Comment by clearloop** [comment]
> Can you elaborate on this? Can we use the Members storage of the committee?

Sure, for example, we can add a `MemberPermission` field to `CommitteeMember`

https://github.com/ChainSafe/PINT/blob/455d3f0655abfa6ad3cda569254fa7aa18d23f5b/pallets/committee/src/types.rs#L41-L46


```rust
pub enum MemberPermission {
    All,
    ProposalSubmission,
    ProposalExecution,
    None,
}

pub struct CommitteeMember<AccountId> {
    pub account: AccountId,
    pub member_type: MemberType,
    pub member_permission: MemberPermission
}

struct EnsureMember {
  // ...
}

impl EnsureOrigin for EnsureMember {
  // ...
}
```
